# Generated by Django 4.2.4 on 2024-01-27 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0014_remove_resourcesmodel_article_resourcesmodel_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentmodel',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolioapp.portfoliomodel'),
        ),
    ]
