# Generated by Django 4.2.4 on 2024-01-27 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0015_alter_investmentmodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentmodel',
            name='contact_no',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portfolioapp.portfoliomodel'),
        ),
        migrations.AlterField(
            model_name='investmentmodel',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
