# Generated by Django 4.2.4 on 2024-01-27 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0016_investmentmodel_contact_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentmodel',
            name='contact_no',
        ),
    ]
