# Generated by Django 4.2.4 on 2024-01-27 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0017_remove_investmentmodel_contact_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentmodel',
            name='contact_no',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portfolioapp.portfoliomodel'),
        ),
    ]
