# Generated by Django 4.2.4 on 2024-01-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0020_transactionlogmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipmodel',
            name='mem_id',
            field=models.IntegerField(auto_created=True),
        ),
    ]
