# Generated by Django 4.2.4 on 2024-01-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0021_alter_membershipmodel_mem_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='membershipmodel',
            name='mem_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
