# Generated by Django 4.2.4 on 2024-01-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0024_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentmarketmodel',
            name='stockamt',
            field=models.FloatField(),
        ),
    ]
